### ISSUE TITLE
Better Questing LAN Not Letting Claim Reward/ Natural Research Meat

### ISSUE THREAD

**Issue by Dartendal** [CaiganMythFang/TheFerretBusinessIssues#14]
Howdy! I'm playing through the pack with my fiancee over LAN and the quests Technology Research and Natural Research would not let me claim the rewards, even though it shows as complete. Her PC is the host, mine is connecting. We worked around it by using one of the commands to complete the quests which let me claim the rewards, but the quests are still showing as blue. I just wanted to pass along what happened, in case there's something on your end to figure out about the quests or whatever.

Edit: Looks like it's affecting all of the quests. Won't let me turn in things for the quests or claim rewards. We had a connection issue at one point which caused my ID to change, so we had to fix that. Could that have caused the issue? We've started a new world because only one person being able to complete quests and claim rewards is terribly inconvenient and are hoping that a new world will solve the issue. We're keeping the world with the issues, in case that would be helpful. Something I forgot to mention is that it was working earlier, we were in a party and were both able to turn in items for quests and claim rewards. The settings remained unchanged, it just kinda stopped working as expected.

Natural Research quest does not accept big bird meat or small bird meat from exotic birds mod. Not sure if intended.

**Comment by CaiganMythFang** [comment]
Yeah, if your UUID changes, it can break questing since BQ tracks via UUID. 

You also cannot currently run the server or the clients in Offline mode (check the server.properties). This makes it impossible to quest properly due to an issue with BQ (which will be fixed in the next major Better Questing update actually).

Rarely, though, a quest will break for an unknown reason as of yet. The commands will sort that out, and hopefully that issue will also be fixed in the next major BQ update.

As for the quest, I've noted it down to fix later. =)
