### ISSUE TITLE
Crashes upon startup and loading save file after recent power outage

### ISSUE THREAD

**Issue by koka558** [CaiganMythFang/TheFerretBusinessIssues#41]
I was in the middle of my game yesterday when the power went out for multiple hours. When I tried starting up The Ferret Business, the game would crash back to the launcher. The console said to disable ae2stuff-rv3, which I did. The game loaded until it eventually told me that that pack was required. I then made a copy of "The Ferret Business" as well as my save file. I reinstalled the pack, and it started up fine. When I tried reloading my save file, it crashes back to the loader. 

I have attached below the console readout after the crash I get when I try to load my save file (I'm new here, so if there is a better way to do this, let me know). I can also try to replicate the crash from before I reinstalled the game, if that is any use. 

Any ideas on how to get my game back?

PS: during the game, it occasionally says that it is doing a server backup. Are those backups stored somewhere that I could get to them now? I couldn't figure out which mod was even making the backups.

[Console readout.txt](https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/846631/Console.readout.txt)

**Comment by CaiganMythFang** [comment]
Ah, what happened is your worlds HQM questing progress got corrupted.  You'll need to reset it.

You can reach your install folder with [these instructions](https://github.com/CaiganMythFang/TheFerretBusinessIssues/issues/1), since it depends on which launcher you are using.

Instructions on how to reset it can be found [here](https://github.com/CaiganMythFang/TheFerretBusinessIssues/issues/2).

Server backups can be found in your minecraft/ftbutil-backups/ folder.

**Comment by koka558** [comment]
Thank you thank you! I was so annoyed at the power company! It looks like that let me open my game again, but, even after inputting the /hqm quest command, the quest tablet still is empty, and my only options are to edit it. I found out that I actually had a backup that was almost right where I was before the power outage, so I am using that, and it works great. Thank you!

**Comment by CaiganMythFang** [comment]
Good to hear!
