### ISSUE TITLE
"java.util.ConcurrentModificationException" Crash on world load

### ISSUE THREAD

**Issue by joecharamut** [CaiganMythFang/TheFerretBusinessIssues#43]
Only happens the second time I load my world though. 
[crash-2017-04-11_07.00.38-server.txt](https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/912931/crash-2017-04-11_07.00.38-server.txt)
[log.txt](https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/912932/log.txt)

**Comment by joecharamut** [comment]
I am using the curse launcher if it matters

**Comment by CaiganMythFang** [comment]
Sorry for taking so long getting back to you!

Is this from a world that existed before the 0.2.2 update, or is this with a new world?

**Comment by joecharamut** [comment]
It was created after the update.

**Comment by CaiganMythFang** [comment]
Okay, looking into it, this seems to be a rare issue fixed with a newer version of Better Questing.

This isn't as easy as updating all your own files to the latest BQ version, as that's jumping from BQ1 (which the pack is on) to BQ2, which I haven't tested yet, so I don't know if it works or what I have to change to get it to work.

I'll look into what can be done, but you might have to wait till the next pack update.
