### ISSUE TITLE
Crash on world load (java.lang.NullPointerException: Exception in server tick loop)

### ISSUE THREAD

**Issue by lolman360** [CaiganMythFang/TheFerretBusinessIssues#45]
I get a NullPointerException every time i try to load a world that is already created (creating a world works fine). 
A pastebin to the whole crash report https://pastebin.com/YzyuCjda

**Comment by CaiganMythFang** [comment]
You need to reset your HQM progress following these instructions :
https://github.com/CaiganMythFang/TheFerretBusinessIssues/issues/2

Some of the HQM stuff (corporate catalog)  was reworked last few updates,
older worlds sometimes have issues updating.

Since actual questing is done in BQ, all this does is reset the instruction
quests.

**Comment by lolman360** [comment]
Thanks for your prompt support
It now gets a 

java.lang.ArrayIndexOutOfBoundsException: -7


error however.
Now, the  HQM folder has been deleted and via the link that you have supplied, it syas that deleting the HQM folder is the solution however no such folder exists.

**Comment by CaiganMythFang** [comment]
Post up the new paste bin for me? Need to see the rest of the error log to
find out what's breaking

**Comment by lolman360** [comment]
https://pastebin.com/b6HtPwQK
\

**Comment by CaiganMythFang** [comment]
Hm, that's still the same error. Make sure you are deleting it from the
correct world folder, as well

**Comment by lolman360** [comment]
I've tired multiple things short of running it on the downloaded server program locally. I'll try that, see if it works.
