### ISSUE TITLE
Draconic Evolution Repeatable quest non-repeatable

### ISSUE THREAD

**Issue by KahnWolfe** [CaiganMythFang/TheFerretBusinessIssues#55]
I am glad to see we can access Draconic Evolution again. Sadly, seem to have found a hang up in that the quest to get the draconic core can only be completed once, whereas you need several in order to continue the line in the book and get said items. Running on an MP server it isn't too much an issue for me as I can just throw away money and op myself the items, but it could be quite frustrating in SP if one did not enable cheats.

**Comment by CaiganMythFang** [comment]
Currently the repeat ability of all quests in the QUEST Tablet are disabled due to a BQ2 bug.

When you have any Draconic Evolution item in your inventory, open your TFB Corporate Catalog to see if it unlocks one of the repeat quests in this.

Hopefully by next major update I'll have a better fix for this.

**Comment by KahnWolfe** [comment]
Yes I found it later, feel like a buffoon. However ya might want to put a line of text in the QUEST tablet that mentions looking in your TFB Catalog. Thanks for the quick reply.

**Comment by CaiganMythFang** [comment]
I have reverted the change from last update, and included a workaround to make repeatable quests work again in the next update, so that use of the Corporate Catalog is no longer necessary.

**Comment by CaiganMythFang** [comment]
Fixed in 0.2.6
