### ISSUE TITLE
Unable to see all quests in tabs

### ISSUE THREAD

**Issue by Super5wan** [CaiganMythFang/TheFerretBusinessIssues#68]
I have looked for ages trying to find out if there is a post for this issue, and I can't find anything.
When I open a tab in the quest book, I am unable to see all the quests and when I click and drag the window, I can see the end of the quest line, but nothing before it.
I am using the Forever Stranded Lost Souls modpack.
I tried /bq_admin default load, updating Java, uninstalling and re-installing, but the problem persists.

Also, I'm getting the bouncy scroll issue that seems to be quite common. Still unaware of a fix,

Edit: Here is a screen shot of all I can see on the "Survival" tab: 
![2018-03-04_22 00 31](https://user-images.githubusercontent.com/37051322/36951096-43fb5330-1ff7-11e8-9eea-8e08ba80f1b0.png)

**Comment by CaiganMythFang** [comment]
As I am not the dev for the Forever Stranded Lost Souls modpack, I don't know how they have set up their modpack's quests, nor help with many issues with BQ2 outside of the 1.7 version as the Better Questing dev is done updating the 1.7 branch for now.

The scroll issue is something known to the Better Questing dev, and one of the usual causes are quests with cooldown periods (repeatable quests) and similar in BQ2 versions. It won't be fixed in 1.7 versions of Better Questing, but is planned to be fixed in Better Questing 3 apparently.
