### ISSUE TITLE
MultiMC silently fails to download/import pack's mods during import

### ISSUE THREAD

**Issue by jmcaffee** [CaiganMythFang/TheFerretBusinessIssues#87]
Issue while importing downloaded zip file (`TheFerretBusiness-0.2.6-1.7.10.zip`) into MultiMC.

MMC does not attempt to download mods within the manifest.

Upon examination of the zip file, it appears to contain both an `overrides` folder and a `overridessiness 01.1 FINAL BETA` folder. The existence of this additional artifact confuses MMC's import/download mechanism. Deleting this folder (leaving `overrides` alone) from the `zip` file and re-importing seems to fix the issue.

**Comment by CaiganMythFang** [comment]
Interesting, I'm not sure why that folder is in there like that. 

Unfortunately I don't fully control the Twitch side of the Ferret Business 1 uploads, since its originally a FTB launcher pack that's grandfathered into being on Twitch as well, and has the old permission rules assigned to it (some mods aren't allowed normally on twitch otherwise)

I'll note this and see what I can do with the upcoming update. It might be something the MultiMC team may need to know as well, since just having that folder probably shouldn't fail the import process silently.
